//
// Generated file, do not edit! Created by nedtool 5.6 from mvsc3.msg.
//

#ifndef __MVSC3_M_H
#define __MVSC3_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>mvsc3.msg:18</tt> by nedtool.
 * <pre>
 * message MvScMsg
 * {
 *     int source;
 *     int status;
 *     int coords;
 *     int time;
 * 
 * }
 * </pre>
 */
class MvScMsg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int status;
    int coords;
    int time;

  private:
    void copy(const MvScMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MvScMsg&);

  public:
    MvScMsg(const char *name=nullptr, short kind=0);
    MvScMsg(const MvScMsg& other);
    virtual ~MvScMsg();
    MvScMsg& operator=(const MvScMsg& other);
    virtual MvScMsg *dup() const override {return new MvScMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getStatus() const;
    virtual void setStatus(int status);
    virtual int getCoords() const;
    virtual void setCoords(int coords);
    virtual int getTime() const;
    virtual void setTime(int time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MvScMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MvScMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MVSC3_M_H

